package permission

type Definition struct {
	ParentCode  string
	Code        string
	Name        string
	Type        string
	Path        string
	Method      string
	Component   string
	Icon        string
	Description string
	Status      int64
	Sort        int64
}

func BuiltinDefinitions() []Definition {
	return []Definition{
		{
			Code:        "dashboard",
			Name:        "Dashboard",
			Type:        "menu",
			Path:        "/dashboard",
			Component:   "dashboard/index",
			Icon:        "dashboard",
			Description: "Dashboard menu",
			Status:      1,
			Sort:        1,
		},
		{
			Code:        "dashboard.read",
			Name:        "Read Dashboard Overview",
			Type:        "api",
			Path:        "/api/v1/dashboard/overview",
			Method:      "GET",
			Description: "Read aggregated operational dashboard metrics",
			Status:      1,
			Sort:        2,
		},
		{
			Code:        "business",
			Name:        "Business",
			Type:        "menu",
			Path:        "/business",
			Component:   "Layout",
			Icon:        "appstore",
			Description: "Business root menu",
			Status:      1,
			Sort:        5,
		},
		{
			ParentCode:  "business",
			Code:        "business.spot.review",
			Name:        "Spot Reviews",
			Type:        "menu",
			Path:        "spot-reviews",
			Component:   "spot/review/index",
			Icon:        "audit",
			Description: "Fishing spot review menu",
			Status:      1,
			Sort:        6,
		},
		{
			ParentCode:  "business",
			Code:        "business.public.spot.application",
			Name:        "Public Spot Applications",
			Type:        "menu",
			Path:        "public-spot-applications",
			Component:   "spot/public-application/index",
			Icon:        "audit",
			Description: "Public fishing spot application review menu",
			Status:      1,
			Sort:        7,
		},
		{
			ParentCode:  "business",
			Code:        "business.banner",
			Name:        "Discover Banners",
			Type:        "menu",
			Path:        "banners",
			Component:   "content/banner/index",
			Icon:        "picture",
			Description: "Discover event banner management menu",
			Status:      1,
			Sort:        8,
		},
		{
			ParentCode:  "business",
			Code:        "business.spot.correction",
			Name:        "Spot Corrections",
			Type:        "menu",
			Path:        "spot-corrections",
			Component:   "spot/correction/index",
			Icon:        "edit",
			Description: "Spot correction review menu",
			Status:      1,
			Sort:        7,
		},
		{
			ParentCode:  "business",
			Code:        "business.article",
			Name:        "Articles",
			Type:        "menu",
			Path:        "articles",
			Component:   "article/index",
			Icon:        "document",
			Description: "Discover article management menu",
			Status:      1,
			Sort:        7,
		},
		{
			ParentCode:  "business",
			Code:        "business.species",
			Name:        "Species",
			Type:        "menu",
			Path:        "species",
			Component:   "species/index",
			Icon:        "fish",
			Description: "Species management menu",
			Status:      1,
			Sort:        8,
		},
		{
			ParentCode:  "business",
			Code:        "business.user",
			Name:        "Users",
			Type:        "menu",
			Path:        "users",
			Component:   "user/index",
			Icon:        "team",
			Description: "Business user management menu",
			Status:      1,
			Sort:        9,
		},
		{
			Code:        "system",
			Name:        "System",
			Type:        "menu",
			Path:        "/system",
			Component:   "Layout",
			Icon:        "setting",
			Description: "System root menu",
			Status:      1,
			Sort:        10,
		},
		{
			ParentCode:  "system",
			Code:        "system.user",
			Name:        "User Management",
			Type:        "menu",
			Path:        "user",
			Component:   "system/user/index",
			Icon:        "users",
			Description: "User management menu",
			Status:      1,
			Sort:        11,
		},
		{
			ParentCode:  "system",
			Code:        "system.role",
			Name:        "Role Management",
			Type:        "menu",
			Path:        "role",
			Component:   "system/role/index",
			Icon:        "shield",
			Description: "Role management menu",
			Status:      1,
			Sort:        12,
		},
		{
			ParentCode:  "system",
			Code:        "system.permission",
			Name:        "Permission Management",
			Type:        "menu",
			Path:        "permission",
			Component:   "system/permission/index",
			Icon:        "lock",
			Description: "Permission management menu",
			Status:      1,
			Sort:        13,
		},
		{
			Code:        "auth.me.read",
			Name:        "Read Current User",
			Type:        "api",
			Path:        "/api/v1/auth/me",
			Method:      "GET",
			Description: "Read current login user",
			Status:      1,
			Sort:        100,
		},
		{
			Code:        "auth.permission.read",
			Name:        "Read Current Permissions",
			Type:        "api",
			Path:        "/api/v1/auth/permissions",
			Method:      "GET",
			Description: "Read current permission codes",
			Status:      1,
			Sort:        101,
		},
		{
			Code:        "auth.menu.read",
			Name:        "Read Current Menus",
			Type:        "api",
			Path:        "/api/v1/auth/menus",
			Method:      "GET",
			Description: "Read current menu tree",
			Status:      1,
			Sort:        102,
		},
		{
			Code:        "spot.review.read",
			Name:        "Read Spot Reviews",
			Type:        "api",
			Path:        "/api/v1/spots/reviews",
			Method:      "GET",
			Description: "Read fishing spot review list and detail",
			Status:      1,
			Sort:        103,
		},
		{
			Code:        "spot.review.approve",
			Name:        "Approve Spot Review",
			Type:        "api",
			Path:        "/api/v1/spots/reviews/:spotId/approve",
			Method:      "POST",
			Description: "Approve fishing spot review",
			Status:      1,
			Sort:        104,
		},
		{
			Code:        "spot.review.reject",
			Name:        "Reject Spot Review",
			Type:        "api",
			Path:        "/api/v1/spots/reviews/:spotId/reject",
			Method:      "POST",
			Description: "Reject fishing spot review",
			Status:      1,
			Sort:        105,
		},
		{
			Code:        "spot.correction.read",
			Name:        "Read Spot Corrections",
			Type:        "api",
			Path:        "/api/v1/spot-corrections",
			Method:      "GET",
			Description: "Read user submitted spot corrections",
			Status:      1,
			Sort:        106,
		},
		{
			Code:        "spot.correction.review",
			Name:        "Review Spot Corrections",
			Type:        "api",
			Path:        "/api/v1/spot-corrections/:correctionId/(approve|reject)",
			Method:      "POST",
			Description: "Approve or reject a spot correction",
			Status:      1,
			Sort:        107,
		},
		{
			Code:        "article.read",
			Name:        "Read Articles",
			Type:        "api",
			Path:        "/api/v1/articles",
			Method:      "GET",
			Description: "Read article list and detail",
			Status:      1,
			Sort:        106,
		},
		{
			Code:        "article.create",
			Name:        "Create Article",
			Type:        "api",
			Path:        "/api/v1/articles",
			Method:      "POST",
			Description: "Create article",
			Status:      1,
			Sort:        107,
		},
		{
			Code:        "article.update",
			Name:        "Update Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId",
			Method:      "PUT",
			Description: "Update article",
			Status:      1,
			Sort:        108,
		},
		{
			Code:        "article.publish",
			Name:        "Publish Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId/publish",
			Method:      "POST",
			Description: "Publish article",
			Status:      1,
			Sort:        109,
		},
		{
			Code:        "article.offline",
			Name:        "Offline Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId/offline",
			Method:      "POST",
			Description: "Offline article",
			Status:      1,
			Sort:        110,
		},
		{
			Code:        "species.read",
			Name:        "Read Species",
			Type:        "api",
			Path:        "/api/v1/species",
			Method:      "GET",
			Description: "Read species list and detail",
			Status:      1,
			Sort:        111,
		},
		{
			Code:        "species.create",
			Name:        "Create Species",
			Type:        "api",
			Path:        "/api/v1/species",
			Method:      "POST",
			Description: "Create species",
			Status:      1,
			Sort:        112,
		},
		{
			Code:        "species.update",
			Name:        "Update Species",
			Type:        "api",
			Path:        "/api/v1/species/:speciesId",
			Method:      "PUT",
			Description: "Update species",
			Status:      1,
			Sort:        113,
		},
		{
			Code:        "species.visibility.update",
			Name:        "Update Species Visibility",
			Type:        "api",
			Path:        "/api/v1/species/:speciesId/visibility",
			Method:      "POST",
			Description: "Update species visibility",
			Status:      1,
			Sort:        114,
		},
		{
			Code:        "user.read",
			Name:        "Read Users",
			Type:        "api",
			Path:        "/api/v1/users",
			Method:      "GET",
			Description: "Read business user list and detail",
			Status:      1,
			Sort:        115,
		},
		{
			Code:        "user.status.update",
			Name:        "Update User Status",
			Type:        "api",
			Path:        "/api/v1/users/:userId/status",
			Method:      "POST",
			Description: "Update business user status",
			Status:      1,
			Sort:        116,
		},
		{
			Code:        "rbac.user.read",
			Name:        "Read User Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/users/:userId/roles",
			Method:      "GET",
			Description: "Read user role assignments",
			Status:      1,
			Sort:        117,
		},
		{
			Code:        "admin.user.create",
			Name:        "Create Admin User",
			Type:        "api",
			Path:        "/api/v1/admin/users",
			Method:      "POST",
			Description: "Create an administrator account",
			Status:      1,
			Sort:        118,
		},
		{
			Code:        "admin.user.update",
			Name:        "Update Admin User",
			Type:        "api",
			Path:        "/api/v1/admin/users/:userId",
			Method:      "PUT",
			Description: "Update administrator profile and status",
			Status:      1,
			Sort:        119,
		},
		{
			Code:        "admin.user.password.update",
			Name:        "Reset Admin Password",
			Type:        "api",
			Path:        "/api/v1/admin/users/:userId/password",
			Method:      "POST",
			Description: "Reset administrator password",
			Status:      1,
			Sort:        120,
		},
		{
			Code:        "rbac.user.update",
			Name:        "Update User Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/users/:userId/roles",
			Method:      "PUT",
			Description: "Update user role assignments",
			Status:      1,
			Sort:        121,
		},
		{
			Code:        "rbac.role.read",
			Name:        "Read Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/roles",
			Method:      "GET",
			Description: "Read role list",
			Status:      1,
			Sort:        122,
		},
		{
			Code:        "rbac.role.create",
			Name:        "Create Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/roles",
			Method:      "POST",
			Description: "Create a role",
			Status:      1,
			Sort:        123,
		},
		{
			Code:        "rbac.role.update",
			Name:        "Update Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/roles/:roleId",
			Method:      "PUT",
			Description: "Update a role",
			Status:      1,
			Sort:        124,
		},
		{
			Code:        "rbac.role.delete",
			Name:        "Delete Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/roles/:roleId",
			Method:      "DELETE",
			Description: "Delete a role",
			Status:      1,
			Sort:        125,
		},
		{
			Code:        "rbac.permission.read",
			Name:        "Read Permissions",
			Type:        "api",
			Path:        "/api/v1/rbac/permissions",
			Method:      "GET",
			Description: "Read permission list",
			Status:      1,
			Sort:        126,
		},
		{
			Code:        "rbac.role.permissions.update",
			Name:        "Update Role Permissions",
			Type:        "api",
			Path:        "/api/v1/rbac/roles/:roleId/permissions",
			Method:      "PUT",
			Description: "Update role permission assignments",
			Status:      1,
			Sort:        127,
		},
		{
			Code:        "review.task.read",
			Name:        "Read Review Tasks",
			Type:        "api",
			Path:        "/api/v1/review-tasks",
			Method:      "GET",
			Description: "Read unified review tasks",
			Status:      1,
			Sort:        128,
		},
		{
			Code:        "review.task.export",
			Name:        "Export Audit Logs",
			Type:        "api",
			Path:        "/api/v1/audit-logs/export",
			Method:      "GET",
			Description: "Export filtered admin audit logs as CSV",
			Status:      1,
			Sort:        129,
		},
		{
			Code:        "public.fishing_report.approve",
			Name:        "Approve Public Fishing Report",
			Type:        "api",
			Path:        "/api/v1/review-tasks/public-reports/:recordId/approve",
			Method:      "POST",
			Description: "Approve a user-submitted public fishing report",
			Status:      1,
			Sort:        130,
		},
		{
			Code:        "public.fishing_report.reject",
			Name:        "Reject Public Fishing Report",
			Type:        "api",
			Path:        "/api/v1/review-tasks/public-reports/:recordId/reject",
			Method:      "POST",
			Description: "Reject a user-submitted public fishing report",
			Status:      1,
			Sort:        131,
		},
		{
			Code:        "media.asset.read",
			Name:        "Read Media Review Queue",
			Type:        "api",
			Path:        "/api/v1/media-assets",
			Method:      "GET",
			Description: "Read public fishing record image review queue",
			Status:      1,
			Sort:        132,
		},
		{
			Code:        "media.asset.approve",
			Name:        "Approve Media Asset",
			Type:        "api",
			Path:        "/api/v1/media-assets/:mediaId/approve",
			Method:      "POST",
			Description: "Approve a public fishing record image",
			Status:      1,
			Sort:        133,
		},
		{
			Code:        "media.asset.reject",
			Name:        "Reject Media Asset",
			Type:        "api",
			Path:        "/api/v1/media-assets/:mediaId/reject",
			Method:      "POST",
			Description: "Reject a public fishing record image",
			Status:      1,
			Sort:        134,
		},
		{
			Code:        "public.spot.application.read",
			Name:        "Read Public Spot Applications",
			Type:        "api",
			Path:        "/api/v1/public-spot-applications",
			Method:      "GET",
			Description: "Read user-submitted public fishing spot applications",
			Status:      1,
			Sort:        135,
		},
		{
			Code:        "public.spot.application.approve",
			Name:        "Approve Public Spot Application",
			Type:        "api",
			Path:        "/api/v1/public-spot-applications/:applicationId/approve",
			Method:      "POST",
			Description: "Approve and publish or merge a public fishing spot application",
			Status:      1,
			Sort:        136,
		},
		{
			Code:        "public.spot.application.reject",
			Name:        "Reject Public Spot Application",
			Type:        "api",
			Path:        "/api/v1/public-spot-applications/:applicationId/reject",
			Method:      "POST",
			Description: "Reject a public fishing spot application",
			Status:      1,
			Sort:        137,
		},
		{
			Code:        "banner.read",
			Name:        "Read Discover Banners",
			Type:        "api",
			Path:        "/api/v1/banners",
			Method:      "GET",
			Description: "Read discover event banners",
			Status:      1,
			Sort:        138,
		},
		{
			Code:        "banner.create",
			Name:        "Create Discover Banner",
			Type:        "api",
			Path:        "/api/v1/banners",
			Method:      "POST",
			Description: "Create a discover event banner",
			Status:      1,
			Sort:        139,
		},
		{
			Code:        "banner.update",
			Name:        "Update Discover Banner",
			Type:        "api",
			Path:        "/api/v1/banners/:bannerId",
			Method:      "PUT",
			Description: "Update a discover event banner",
			Status:      1,
			Sort:        140,
		},
		{
			Code:        "banner.visibility.update",
			Name:        "Publish Discover Banner",
			Type:        "api",
			Path:        "/api/v1/banners/:bannerId/visibility",
			Method:      "POST",
			Description: "Publish or hide a discover event banner",
			Status:      1,
			Sort:        141,
		},
	}
}
