package permission

type Definition struct {
	ParentCode  string
	Code        string
	Name        string
	Type        string
	Path        string
	Method      string
	Component   string
	Icon        string
	Description string
	Status      int64
	Sort        int64
}

func BuiltinDefinitions() []Definition {
	return []Definition{
		{
			Code:        "dashboard",
			Name:        "Dashboard",
			Type:        "menu",
			Path:        "/dashboard",
			Component:   "dashboard/index",
			Icon:        "dashboard",
			Description: "Dashboard menu",
			Status:      1,
			Sort:        1,
		},
		{
			Code:        "business",
			Name:        "Business",
			Type:        "menu",
			Path:        "/business",
			Component:   "Layout",
			Icon:        "appstore",
			Description: "Business root menu",
			Status:      1,
			Sort:        5,
		},
		{
			ParentCode:  "business",
			Code:        "business.spot.review",
			Name:        "Spot Reviews",
			Type:        "menu",
			Path:        "spot-reviews",
			Component:   "spot/review/index",
			Icon:        "audit",
			Description: "Fishing spot review menu",
			Status:      1,
			Sort:        6,
		},
		{
			ParentCode:  "business",
			Code:        "business.spot.correction",
			Name:        "Spot Corrections",
			Type:        "menu",
			Path:        "spot-corrections",
			Component:   "spot/correction/index",
			Icon:        "edit",
			Description: "Spot correction review menu",
			Status:      1,
			Sort:        7,
		},
		{
			ParentCode:  "business",
			Code:        "business.article",
			Name:        "Articles",
			Type:        "menu",
			Path:        "articles",
			Component:   "article/index",
			Icon:        "document",
			Description: "Discover article management menu",
			Status:      1,
			Sort:        7,
		},
		{
			ParentCode:  "business",
			Code:        "business.species",
			Name:        "Species",
			Type:        "menu",
			Path:        "species",
			Component:   "species/index",
			Icon:        "fish",
			Description: "Species management menu",
			Status:      1,
			Sort:        8,
		},
		{
			ParentCode:  "business",
			Code:        "business.user",
			Name:        "Users",
			Type:        "menu",
			Path:        "users",
			Component:   "user/index",
			Icon:        "team",
			Description: "Business user management menu",
			Status:      1,
			Sort:        9,
		},
		{
			Code:        "system",
			Name:        "System",
			Type:        "menu",
			Path:        "/system",
			Component:   "Layout",
			Icon:        "setting",
			Description: "System root menu",
			Status:      1,
			Sort:        10,
		},
		{
			ParentCode:  "system",
			Code:        "system.user",
			Name:        "User Management",
			Type:        "menu",
			Path:        "user",
			Component:   "system/user/index",
			Icon:        "users",
			Description: "User management menu",
			Status:      1,
			Sort:        11,
		},
		{
			ParentCode:  "system",
			Code:        "system.role",
			Name:        "Role Management",
			Type:        "menu",
			Path:        "role",
			Component:   "system/role/index",
			Icon:        "shield",
			Description: "Role management menu",
			Status:      1,
			Sort:        12,
		},
		{
			ParentCode:  "system",
			Code:        "system.permission",
			Name:        "Permission Management",
			Type:        "menu",
			Path:        "permission",
			Component:   "system/permission/index",
			Icon:        "lock",
			Description: "Permission management menu",
			Status:      1,
			Sort:        13,
		},
		{
			Code:        "auth.me.read",
			Name:        "Read Current User",
			Type:        "api",
			Path:        "/api/v1/auth/me",
			Method:      "GET",
			Description: "Read current login user",
			Status:      1,
			Sort:        100,
		},
		{
			Code:        "auth.permission.read",
			Name:        "Read Current Permissions",
			Type:        "api",
			Path:        "/api/v1/auth/permissions",
			Method:      "GET",
			Description: "Read current permission codes",
			Status:      1,
			Sort:        101,
		},
		{
			Code:        "auth.menu.read",
			Name:        "Read Current Menus",
			Type:        "api",
			Path:        "/api/v1/auth/menus",
			Method:      "GET",
			Description: "Read current menu tree",
			Status:      1,
			Sort:        102,
		},
		{
			Code:        "spot.review.read",
			Name:        "Read Spot Reviews",
			Type:        "api",
			Path:        "/api/v1/spots/reviews",
			Method:      "GET",
			Description: "Read fishing spot review list and detail",
			Status:      1,
			Sort:        103,
		},
		{
			Code:        "spot.review.approve",
			Name:        "Approve Spot Review",
			Type:        "api",
			Path:        "/api/v1/spots/reviews/:spotId/approve",
			Method:      "POST",
			Description: "Approve fishing spot review",
			Status:      1,
			Sort:        104,
		},
		{
			Code:        "spot.review.reject",
			Name:        "Reject Spot Review",
			Type:        "api",
			Path:        "/api/v1/spots/reviews/:spotId/reject",
			Method:      "POST",
			Description: "Reject fishing spot review",
			Status:      1,
			Sort:        105,
		},
		{
			Code:        "spot.correction.read",
			Name:        "Read Spot Corrections",
			Type:        "api",
			Path:        "/api/v1/spot-corrections",
			Method:      "GET",
			Description: "Read user submitted spot corrections",
			Status:      1,
			Sort:        106,
		},
		{
			Code:        "spot.correction.review",
			Name:        "Review Spot Corrections",
			Type:        "api",
			Path:        "/api/v1/spot-corrections/:correctionId/(approve|reject)",
			Method:      "POST",
			Description: "Approve or reject a spot correction",
			Status:      1,
			Sort:        107,
		},
		{
			Code:        "article.read",
			Name:        "Read Articles",
			Type:        "api",
			Path:        "/api/v1/articles",
			Method:      "GET",
			Description: "Read article list and detail",
			Status:      1,
			Sort:        106,
		},
		{
			Code:        "article.create",
			Name:        "Create Article",
			Type:        "api",
			Path:        "/api/v1/articles",
			Method:      "POST",
			Description: "Create article",
			Status:      1,
			Sort:        107,
		},
		{
			Code:        "article.update",
			Name:        "Update Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId",
			Method:      "PUT",
			Description: "Update article",
			Status:      1,
			Sort:        108,
		},
		{
			Code:        "article.publish",
			Name:        "Publish Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId/publish",
			Method:      "POST",
			Description: "Publish article",
			Status:      1,
			Sort:        109,
		},
		{
			Code:        "article.offline",
			Name:        "Offline Article",
			Type:        "api",
			Path:        "/api/v1/articles/:articleId/offline",
			Method:      "POST",
			Description: "Offline article",
			Status:      1,
			Sort:        110,
		},
		{
			Code:        "species.read",
			Name:        "Read Species",
			Type:        "api",
			Path:        "/api/v1/species",
			Method:      "GET",
			Description: "Read species list and detail",
			Status:      1,
			Sort:        111,
		},
		{
			Code:        "species.create",
			Name:        "Create Species",
			Type:        "api",
			Path:        "/api/v1/species",
			Method:      "POST",
			Description: "Create species",
			Status:      1,
			Sort:        112,
		},
		{
			Code:        "species.update",
			Name:        "Update Species",
			Type:        "api",
			Path:        "/api/v1/species/:speciesId",
			Method:      "PUT",
			Description: "Update species",
			Status:      1,
			Sort:        113,
		},
		{
			Code:        "species.visibility.update",
			Name:        "Update Species Visibility",
			Type:        "api",
			Path:        "/api/v1/species/:speciesId/visibility",
			Method:      "POST",
			Description: "Update species visibility",
			Status:      1,
			Sort:        114,
		},
		{
			Code:        "user.read",
			Name:        "Read Users",
			Type:        "api",
			Path:        "/api/v1/users",
			Method:      "GET",
			Description: "Read business user list and detail",
			Status:      1,
			Sort:        115,
		},
		{
			Code:        "user.status.update",
			Name:        "Update User Status",
			Type:        "api",
			Path:        "/api/v1/users/:userId/status",
			Method:      "POST",
			Description: "Update business user status",
			Status:      1,
			Sort:        116,
		},
		{
			Code:        "rbac.user.read",
			Name:        "Read User Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/users/:userId/roles",
			Method:      "GET",
			Description: "Read user role assignments",
			Status:      1,
			Sort:        117,
		},
		{
			Code:        "rbac.role.read",
			Name:        "Read Roles",
			Type:        "api",
			Path:        "/api/v1/rbac/roles",
			Method:      "GET",
			Description: "Read role list",
			Status:      1,
			Sort:        118,
		},
		{
			Code:        "rbac.permission.read",
			Name:        "Read Permissions",
			Type:        "api",
			Path:        "/api/v1/rbac/permissions",
			Method:      "GET",
			Description: "Read permission list",
			Status:      1,
			Sort:        119,
		},
	}
}
